---
- unarchive:
    src: "https://wordpress.org/latest.tar.gz"
    dest: "{{ unarc_path }}"
    remote_src: yes

- name: get salt
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "salt"
  become: no
  become_method: sudo

- name: Add wp config
  template:
    src: "templates/wp.conf.j2"
    dest: "{{ unarc_path }}/wordpress/wp-config.php"
    owner: root
    group: root
    mode: 0644
