---
- name: Install Apache
  apt: pkg={{ item }} state=latest
  with_items:
  - apache2
  - libapache2-mod-php

  # _______________Apache config_____________
- name: Add Apache virtualhost
  template:
    src: "templates/vhost.dev.conf.j2"
    dest: "/etc/apache2/sites-available/{{ domain }}.conf"
    owner: root
    group: root
    mode: 0644

- name: Symlink virtualhost to sites-enabled.
  file:
    src: "/etc/apache2/sites-available/{{ domain }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ domain }}.conf"
    state: link

- name: Remove default virtualhost file.
  file:
    path: "/etc/apache2/sites-enabled/000-default.conf"
    state: absent

- name: Deactivate default vhost
  command: a2dissite 000-default
