---
- apt_key:
      keyserver: hkp://ha.pool.sks-keyservers.net:80
      id: 58118E89F3A912897C070ADBF76221572C52609D

- apt_repository:
      repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
      state: present

- name: Update repo
  apt:
      update_cache: yes

#teke unmae -a

- shell: "uname -r"
  ignore_errors: yes
  register: uname_result

- name: Install all ))
  apt: pkg={{ item }} state=latest
  with_items:
      - apt-transport-https
      - ca-certificates
      - linux-image-extra-{{ uname_result.stdout }}
      - linux-image-extra-virtual
      - docker-engine
      - python-docker
