#-*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "ubuntu/xenial64"
	config.vm.network "public_network", ip: "10.10.10.200"

	config.vm.provision "ansible" do |ansible|
    	ansible.playbook = "ansible.yml"
  end
end
