---
- name: Mysql cli and server install
  apt: pkg={{ item }} state=latest
  with_items:
  - mysql-server
  - python-mysqldb

- name: Remove the MySQL test database.
  mysql_db: db=test state=absent

- name: Create a database
  mysql_db: db="{{ database }}" state=present

- name: Setup password for database
  mysql_user:
    name: "{{ dbuser }}"
    password: "{{ dbpass }}"
    host: "localhost"
    priv: "{{ database }}.*:ALL"
    state: present